// Mapa EDITABLE ciudad -> provincia (claves normalizadas: minúsculas sin tildes).
// Solo se asigna provincia cuando la correspondencia es segura.
export const provinceByCity: Record<string, string> = {
  madrid: "Madrid", getafe: "Madrid", coslada: "Madrid", aranjuez: "Madrid",
  navalcarnero: "Madrid", "san sebastian de los reyes": "Madrid",
  barcelona: "Barcelona", palleja: "Barcelona", girona: "Girona",
  tarragona: "Tarragona", lleida: "Lleida", tarrega: "Lleida", cervera: "Lleida",
  valencia: "Valencia", gandia: "Valencia", catarroja: "Valencia",
  "puerto de sagunto": "Valencia", "pto de sagunto": "Valencia",
  "puto de sagunto": "Valencia", sagunto: "Valencia",
  alicante: "Alicante", elda: "Alicante", elche: "Alicante",
  castellon: "Castellón", murcia: "Murcia", cartagena: "Murcia",
  sevilla: "Sevilla", huelva: "Huelva", cadiz: "Cádiz", cordoba: "Córdoba",
  "dona mencia": "Córdoba", granada: "Granada", "la herradura": "Granada",
  malaga: "Málaga", torrox: "Málaga", almeria: "Almería", jaen: "Jaén",
  albacete: "Albacete", almansa: "Albacete", valdeganga: "Albacete",
  iniesta: "Cuenca", cuenca: "Cuenca", "ciudad real": "Ciudad Real",
  membrilla: "Ciudad Real", toledo: "Toledo", guadalajara: "Guadalajara",
  badajoz: "Badajoz", almendralejo: "Badajoz", "valencia del ventoso": "Badajoz",
  caceres: "Cáceres", valladolid: "Valladolid", salamanca: "Salamanca",
  zamora: "Zamora", leon: "León", palencia: "Palencia",
  "cervera de pisuerga": "Palencia", burgos: "Burgos", "miranda de ebro": "Burgos",
  segovia: "Segovia", avila: "Ávila", soria: "Soria",
  bilbao: "Bizkaia", "vitoria": "Álava", "miranda": "Burgos",
  "san sebastian": "Gipuzkoa", pamplona: "Navarra", logrono: "La Rioja",
  haro: "La Rioja", santander: "Cantabria", oviedo: "Asturias",
  gijon: "Asturias", asturias: "Asturias",
  "a coruna": "A Coruña", coruna: "A Coruña", ferrol: "A Coruña",
  lugo: "Lugo", ourense: "Ourense", "o barco de valdeorras": "Ourense",
  pontevedra: "Pontevedra", vigo: "Pontevedra", zaragoza: "Zaragoza",
  huesca: "Huesca", teruel: "Teruel", ceuta: "Ceuta", melilla: "Melilla",
  mallorca: "Illes Balears", "palma de mallorca": "Illes Balears",
  palma: "Illes Balears", ibiza: "Illes Balears",
  tenerife: "Santa Cruz de Tenerife", "las palmas": "Las Palmas",
};

export const communityByProvince: Record<string, string> = {
  Madrid: "Comunidad de Madrid",
  Barcelona: "Cataluña", Girona: "Cataluña", Tarragona: "Cataluña", Lleida: "Cataluña",
  Valencia: "Comunidad Valenciana", Alicante: "Comunidad Valenciana", "Castellón": "Comunidad Valenciana",
  Murcia: "Región de Murcia",
  Sevilla: "Andalucía", Huelva: "Andalucía", "Cádiz": "Andalucía", "Córdoba": "Andalucía",
  Granada: "Andalucía", "Málaga": "Andalucía", "Almería": "Andalucía", "Jaén": "Andalucía",
  Albacete: "Castilla-La Mancha", Cuenca: "Castilla-La Mancha", "Ciudad Real": "Castilla-La Mancha",
  Toledo: "Castilla-La Mancha", Guadalajara: "Castilla-La Mancha",
  Badajoz: "Extremadura", "Cáceres": "Extremadura",
  Valladolid: "Castilla y León", Salamanca: "Castilla y León", Zamora: "Castilla y León",
  "León": "Castilla y León", Palencia: "Castilla y León", Burgos: "Castilla y León",
  Segovia: "Castilla y León", "Ávila": "Castilla y León", Soria: "Castilla y León",
  Bizkaia: "País Vasco", "Álava": "País Vasco", Gipuzkoa: "País Vasco",
  Navarra: "Comunidad Foral de Navarra", "La Rioja": "La Rioja",
  Cantabria: "Cantabria", Asturias: "Principado de Asturias",
  "A Coruña": "Galicia", Lugo: "Galicia", Ourense: "Galicia", Pontevedra: "Galicia",
  Zaragoza: "Aragón", Huesca: "Aragón", Teruel: "Aragón",
  Ceuta: "Ceuta", Melilla: "Melilla",
  "Illes Balears": "Illes Balears",
  "Santa Cruz de Tenerife": "Canarias", "Las Palmas": "Canarias",
};

// Provincias válidas (para reconocer pistas escritas por el usuario)
export const knownProvinces = new Set(Object.values(provinceByCity));
